# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='name as initials on fitbit')),
                ('weight', models.FloatField(verbose_name='weight in lbs')),
                ('date', models.DateTimeField(verbose_name='date taken')),
            ],
        ),
    ]
